# Generated by Django 4.0.1 on 2023-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=20)),
                ('mem_add1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
