# Generated by Django 4.0.1 on 2023-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lprod_id', models.IntegerField(max_length=7)),
                ('lprod_gu', models.CharField(max_length=4)),
                ('lprod_nm', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'lprod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=10)),
                ('prod_name', models.CharField(max_length=40)),
                ('prod_lgu', models.CharField(max_length=4)),
                ('prod_cost', models.IntegerField(max_length=10)),
                ('prod_price', models.IntegerField(max_length=10)),
                ('prod_sale', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'prod',
                'managed': False,
            },
        ),
    ]
