from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('01_html/', views.htmlVeiw01),
    path('02_link/', views.linkView),
    path('03_css/', views.htmlView03),
    path('04_css/', views.cssView04),
    path('05_css/', views.cssView05),
    path('06_css/', views.cssView06),
    path('07_table/', views.tableView),
    path('08_table/', views.tableView02),
    path('09_mem/', views.mem_View),
    path('10_mem_list/', views.mem_View02),
    path('11_ul/', views.ulView),
    path('12_div/', views.divView),
    path('13_div/', views.divView02),
    path('14_iframe/', views.iframeView),
    path('15_cssTable/', views.cssTableView),
    path('16_cssTable/', views.cssTableView02),
    path('17_cssNav/', views.cssNavView),
    path('18_jsInputForm/', views.jsInputFormView),
    path('19_login/', views.jsLogin),
    path('20_radioButton/', views.radioButtonView),
    path('21_radio/', views.jsRadio),
    path('22_radioButton2/', views.radioButton2View2),
    path('23_radio2/', views.jsRadio2),
    path('24_checkbox/', views.checkBoxView),
    path('25_checkbox2/', views.checkBoxView2),
    path('26_selectbox/', views.selectBoxView),
    path('27_selectbox2/', views.selectBoxView2),
    path('28_bootstrap/', views.bootstrapView),
    path('29_bootstrap_table/', views.bootstrapTableView),
    path('30_bootstrap_form/', views.bootstrapFormView),
    path('31_bootstrap_layout/', views.bootstrapLayoutView),
    path('32_include_index/', views.includeindexView),
    path('33_main_index/', views.mainIndexView),
    path('34_extend_layout/', views.extendLayoutView),
    path('35_hello/', views.extendHello),
]